version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "henrry-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-42z1wjjizeev"
s3_prefix = "henrry-test"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
